[package]
name = "paypal-rs"
version = "0.0.1"
authors = ["Edgar <git@edgarluque.com>"]
description = "A library that wraps the paypal api asynchronously."
repository = "https://github.com/edg-l/paypal-rs/"
license = "AGPL-3.0"
license-file = "LICENSE"
keywords = ["paypal", "api", "async"]
categories = ["api-bindings", "asynchronous"]
readme = "README.md"
edition = "2018"


[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
dotenv = "0.15.0"