[package]
name = "paypal-rs"
version = "0.2.0"
authors = ["Edgar <git@edgarluque.com>"]
description = "A library that wraps the paypal api asynchronously."
repository = "https://github.com/edg-l/paypal-rs/"
license = "MIT OR Apache-2.0"
keywords = ["paypal", "api", "async"]
categories = ["api-bindings", "asynchronous"]
documentation = "https://docs.rs/paypal-rs"
readme = "README.md"
edition = "2021"


[dependencies]
reqwest = { version = "0.11.11", default-features = false, features = ["json"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_with = "2.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
jsonwebtoken = "8.1.1"
base64 = "0.13.0"
log = "0.4.17"
bytes = "1.1.0"
derive_builder = "0.11.2"
serde_qs = "0.10.1"

[dev-dependencies]
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
anyhow = "1.0.58"
color-eyre = "0.6.1"

[features]
default = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]
