[package]
name = "paypal-rs"
version = "0.2.0-alpha.7"
authors = ["Edgar <git@edgarluque.com>"]
description = "A library that wraps the paypal api asynchronously."
repository = "https://github.com/edg-l/paypal-rs/"
license = "MIT OR Apache-2.0"
keywords = ["paypal", "api", "async"]
categories = ["api-bindings", "asynchronous"]
documentation = "https://docs.rs/paypal-rs"
readme = "README.md"
edition = "2021"


[dependencies]
reqwest = { version = "0.11.10", default-features = false, features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_with = "1.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
jsonwebtoken = "8.1.0"
base64 = "0.13.0"
log = "0.4.16"
bytes = "1.1.0"
derive_builder = "0.11.2"
serde_qs = "0.9.1"

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
anyhow = "1.0.57"
color-eyre = "0.6.1"

[features]
default = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]
