[package]
name = "paypal-rs"
version = "0.2.0-alpha.5"
authors = ["Edgar <git@edgarluque.com>"]
description = "A library that wraps the paypal api asynchronously."
repository = "https://github.com/edg-l/paypal-rs/"
license = "MIT OR Apache-2.0"
keywords = ["paypal", "api", "async"]
categories = ["api-bindings", "asynchronous"]
documentation = "https://docs.rs/paypal-rs"
readme = "README.md"
edition = "2018"


[dependencies]
reqwest = { version = "0.11.8", features = ["json"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
serde_with = "1.11.0"
chrono = { version = "0.4.19", features = ["serde"] }
jsonwebtoken = "7.2.0"
base64 = "0.13.0"
log = "0.4.14"
bytes = "1.1.0"

[dev-dependencies]
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
