[package]
name = "paypal-rs"
version = "0.0.2"
authors = ["Edgar <git@edgarluque.com>"]
description = "A library that wraps the paypal api asynchronously."
repository = "https://github.com/edg-l/paypal-rs/"
license = "AGPL-3.0"
keywords = ["paypal", "api", "async"]
categories = ["api-bindings", "asynchronous"]
documentation = "https://docs.rs/paypal-rs"
readme = "README.md"
edition = "2018"


[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "7"
base64 = "0.12"
log = "0.4"
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }